name: XcodeBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: xcodebuild -project "ProCICD.xcworkspace" -scheme "Dice" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
